# Generated by Django 3.1.2 on 2021-02-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='static/author_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cytat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('pozytywne', models.IntegerField(default=0)),
                ('negatywne', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
            ],
        ),
    ]
