# Generated by Django 3.1.2 on 2021-02-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='author_images'),
        ),
    ]
