# Generated by Django 3.1.2 on 2021-02-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210213_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propozycje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
            ],
        ),
    ]
